server:
  port: 1111
spring:
  application:
    name: nkop-config-server
  profiles:
    active: native

eureka:
  instance:
    prefer-ip-address:  true
    instance-id:  ${spring.cloud.client.ipAddress}:${server.port}
    hostname: localhost
  client:
    serviceUrl:
      defaultZone:  http://${eureka.instance.hostname}:8888/eureka/