server:
  port: 8888
eureka:
  instance:
    hostname: localhost
    prefer-ip-address:  true
  client:
    registerWithEureka: false
    fetchRegistry:  false
    serviceUrl:
      defaultZone:  http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  application:
    name: nkop-eureka-server

